services:
  - type: web
    name: mohe-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-flash-latest
      - key: KAKAOPAY_CID
        value: TC0ONETIME
      - key: KAKAOPAY_SECRET_KEY
        sync: false
